# Generated by Django 5.0.6 on 2024-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('donador', models.BooleanField(default=False)),
                ('dni', models.CharField(default='--------', max_length=8)),
                ('telefono', models.CharField(default='---------', max_length=9)),
            ],
        ),
    ]
