# Generated by Django 5.0.6 on 2024-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.CharField(default='--------', max_length=8),
        ),
    ]
