# Generated by Django 5.0.6 on 2024-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
