# Generated by Django 5.0.6 on 2024-06-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_persona_donador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=False),
        ),
    ]
